### ISSUE TITLE
secondLayout слишком долго прогружается

### ISSUE THREAD

**Issue by Virg29** [Aqcee/geomarkers#13]
узнать в чем дело,и соответственно оптимизировать до разумного времени

**Comment by Virg29** [comment]
больше не тревожит

**Comment by Aqcee** [comment]
Как почистил?

**Comment by Aqcee** [comment]
Пофиксил *

**Comment by Virg29** [comment]
никак

**Comment by Virg29** [comment]
это видимо было связанно с долгой прогрузкой фрагмента карты
