### ISSUE TITLE
реализация "купола" отслеживания местоположения

### ISSUE THREAD

**Issue by Aqcee** [Aqcee/geomarkers#4]
выделить математические формулы, для постоянного отслеживания местоположения клиента и сопоставление его координат с точкой на карте, дабы выводить уведомления при приближении.

**Comment by Aqcee** [comment]
![09-08-2016 14-34-17](https://cloud.githubusercontent.com/assets/15576320/17514995/dcacb7f0-5e46-11e6-9470-56327a6d7374.png)

**Comment by Virg29** [comment]
готово
